# Generated by Django 4.2.1 on 2023-10-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('challenge_id', models.PositiveIntegerField(blank=True, null=True)),
                ('team_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.CharField(blank=True, max_length=255, null=True)),
                ('ssh_port', models.CharField(blank=True, max_length=255, null=True)),
                ('ssh_user', models.CharField(blank=True, max_length=255, null=True)),
                ('ssh_password', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('visible', models.BooleanField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('is_down', models.BooleanField(blank=True, null=True)),
                ('is_attacked', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'game_boxes',
            },
        ),
    ]
