# Generated by Django 4.2.1 on 2023-10-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebox',
            name='challenge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gamebox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gamebox',
            name='team_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
